language: java

# do not build tagged commits
# this way we avoid rebuilding upon successful deployment (see below)
if: tag IS blank

matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk11
      addons:
        apt:
          packages:
            - clang-format
            - cppcheck
            - libboost-all-dev
            - libfuse-dev
            - rpm
      env:
        - CMAKE_DIST=Linux
        # cmake-<VERSION>-Linux-x86_64/
        - CMAKE_STRIP_COMPONENTS=1
        - GO_DIST=linux
        - LOAD_FUSE_CMD="true"
        - MULTICHAIN_VERSION=2.0.2
        - MULTICHAIN_URL=https://www.multichain.com/download/multichain-${MULTICHAIN_VERSION}.tar.gz
        - UMOUNT_CMD="fusermount"
        - UMOUNT_OPTIONS="-u"

    - os: osx
      osx_image: xcode9.2
      addons:
        homebrew:
          casks:
            - oracle-jdk
            - osxfuse
          packages:
            - boost
            - clang-format
            - cppcheck
          update: true
      env:
        - CMAKE_DIST=Darwin
        # cmake-<VERSION>-Darwin-x86_64/CMake.app/Contents/
        - CMAKE_STRIP_COMPONENTS=3
        - GO_DIST=darwin
        - LOAD_FUSE_CMD="/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse"
        - MULTICHAIN_VERSION=2.0-release
        - MULTICHAIN_TAG=20190521T124426
        - MULTICHAIN_HASH=2bff381
        - MULTICHAIN_URL=https://github.com/paciofs/multichain/releases/download/${MULTICHAIN_VERSION}-${MULTICHAIN_TAG}/multichain-${MULTICHAIN_VERSION}-${MULTICHAIN_HASH}-osx.tar.gz
        - UMOUNT_CMD="diskutil"
        - UMOUNT_OPTIONS="unmount"

    - os: linux
      dist: xenial
      services:
        - docker
      before_install: true
      install: true
      script:
        - docker-compose --log-level INFO --file ./paciofs-docker/docker-compose.yaml build

before_install:
  # load kernel extension on macOS, do nothing otherwise
  - sudo ${LOAD_FUSE_CMD}

  # install CMake, stripping the first N path elements
  - export CMAKE_VERSION="3.14.5"
  - wget --output-document cmake.tar.gz --quiet https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-${CMAKE_DIST}-x86_64.tar.gz
  - sudo mkdir /usr/local/cmake-${CMAKE_VERSION}
  - sudo tar --directory /usr/local/cmake-${CMAKE_VERSION} --extract --file cmake.tar.gz --strip-components ${CMAKE_STRIP_COMPONENTS}
  - rm cmake.tar.gz
  - export PATH="/usr/local/cmake-${CMAKE_VERSION}/bin:${PATH}"

  # install go
  - wget --output-document go.tar.gz --quiet https://dl.google.com/go/go1.12.6.${GO_DIST}-amd64.tar.gz
  - sudo tar --directory /usr/local --extract --file go.tar.gz
  - rm go.tar.gz
  - export GOPATH="${HOME}/go"
  - export GOBIN="${GOPATH}/bin"
  - export PATH="${PATH}:/usr/local/go/bin:${GOBIN}"

  # install dep
  - mkdir -p ${GOBIN}
  - export DEP_RELEASE_TAG="v0.5.0"
  - curl --silent https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  # install gRPC, protoc headers and libraries
  - export GRPC_VERSION="1.18.0"
  - export PROTOBUF_VERSION="3.6.1"
  - git clone --branch v$GRPC_VERSION https://github.com/grpc/grpc.git
  - cd ./grpc && git submodule update --init
  - cd ./third_party/protobuf && git checkout tags/v${PROTOBUF_VERSION} && cd ../../
  # build static gRPC with embeddec c-ares and protobuf, use system ssl and z
  - make HAS_SYSTEM_CARES=false HAS_SYSTEM_PROTOBUF=false -j2 static plugins
  - sudo make install-headers_c install-static_c install-headers_cxx install-static_cxx install-plugins install-certs
  # need to install protoc and include files as well
  - cd ./third_party/protobuf && sudo make install && cd ../../../
  - rm -rf ./grpc

  # install MultiChain
  - wget --output-document multichain.tar.gz --quiet ${MULTICHAIN_URL}
  - sudo tar --directory /usr/local --extract --file multichain.tar.gz
  - rm multichain.tar.gz
  - export MULTICHAIN_HOME="/usr/local/multichain-${MULTICHAIN_VERSION}"

  # for cppcheck-htmlreport
  - pip install --user pygments

install:
  - mvn install --define skipTests=true --define maven.javadoc.skip=true --define protobuf.version=${PROTOBUF_VERSION} --define grpc.version=${GRPC_VERSION} --batch-mode --show-version

script:
  # generate TLS certificates
  - cd ./paciofs-server/src/test/scripts && ./gen-certs.sh && cd ../../../../

  # run tests
  - mvn test --define protobuf.version=${PROTOBUF_VERSION} --define grpc.version=${GRPC_VERSION} --batch-mode

  # start and stop PacioFS
  - mvn --projects paciofs-server exec:java@run-server &
  - MVN_PID=$!
  - sleep 60s

  # create and mount file system
  - ./paciofs-client/target/Release/mkfs.paciofs localhost:8080 volume1 -d TRACE
  - mkdir /tmp/mnt-volume1
  - ./paciofs-client/target/Release/mount.paciofs localhost:8080 /tmp/mnt-volume1 volume1 -o default_permissions -o fsname=paciofs -o noatime -d TRACE &
  - sleep 5s

  # write file
  - cp ./pom.xml /tmp/mnt-volume1
  - sync

  # remount to clear caches
  - ${UMOUNT_CMD} ${UMOUNT_OPTIONS} /tmp/mnt-volume1
  - ./paciofs-client/target/Release/mount.paciofs localhost:8080 /tmp/mnt-volume1 volume1 -o default_permissions -o fsname=paciofs -o noatime -d TRACE &
  - sleep 5s

  # files should not differ
  - diff ./pom.xml /tmp/mnt-volume1/pom.xml; DIFF_EXIT=$?
  - test "0" -eq "${DIFF_EXIT}"

  # unmount
  - ${UMOUNT_CMD} ${UMOUNT_OPTIONS} /tmp/mnt-volume1

  # wait for everyting to shut down
  - kill ${MVN_PID}; wait ${MVN_PID}; MVN_EXIT=$?

  # JVM return code when sent SIGTERM
  - test "143" -eq "${MVN_EXIT}"

after_success:
  # set the tag to enable deployment
  - export TRAVIS_TAG=${TRAVIS_BRANCH}-build

deploy:
  name: "Build of PacioFS ${TRAVIS_BRANCH}"
  body: "Build of https://github.com/paciofs/paciofs/tree/${TRAVIS_COMMIT}"
  provider: releases
  api_key:
    secure: YB55j3A4CCCjRN4gc8b1lo9eFNcvnwJN3SgQduZgF3Lr3no4gompkYO97RBltl7IQZtN6bBcKN/kkxaCHkAwFD0CFF4rOW3TXZMlX6kBrtdPhbvHKICH5w+ccmI6qfE3A3XcmZBiWoru4JZgJVhgGPwb+1Zapb2nWAy/BlIxNtZDbCLcdzlFDKMd9d7VfnoJjHroogjSGZK+Rs9OmruMcl0txPksm4bKtu2X8opu8+iBb3ybDbRsMKh6cYVlXw9Micu8GBoAOCxNkrPFeL2LEawdS27/M0UDDSs6ytTCrLq/ox0fnVDocJqMImxikCHbT7KKmmdTCcO8UavjRH1plpBxrFgRhd3mhigazcF441QspSIB60tO9yZRTaRs1qVKfRKqHcRwqJ24IS7n6DehTFMGBZjj/DWcMpbIQ3L9D0Gr84J9RbEmcfKpjgga8WRwW9HKJ500vfCdxUOfXzheOE1168jdxgB1tfNEIyggbVvskze0iXWg4HEf6FWB9qD+TnRZm8jDOgDHjMkO/gPTN8Rd+4ROfOHsl06mzbZnNhPfhs2xkcW7+DW2B24E+gFDshKoOQ0woSkgihCDjnBNXB2mCNURNbx+e4NGubzlUofUKFFcozds1bIy4DHCOxetAJXljXEaB1oNhkfpDKRlC0CdtDMjt2hR2tOzc9Bt35A=
  # upload generated packages (.deb, .rpm, .pkg)
  file_glob: true
  file: paciofs-client/target/Release/paciofs_client-*
  skip_cleanup: true
  overwrite: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
